nivel1 = {
    "agua": "../niveles/nivel1_csv/nivel1_agua.csv",
    "arbol1": "../niveles/nivel1_csv/nivel1_arbol1.csv",
    "arbol2": "../niveles/nivel1_csv/nivel1_arbol2.csv",
    "arbusto1": "../niveles/nivel1_csv/nivel1_arbusto1.csv",
    "arbusto2": "../niveles/nivel1_csv/nivel1_arbusto2.csv",
    "arbusto3": "../niveles/nivel1_csv/nivel1_arbusto3.csv",
    "arbusto4": "../niveles/nivel1_csv/nivel1_arbusto4.csv",
    "cajas": "../niveles/nivel1_csv/nivel1_cajas.csv",
    "cartel1": "../niveles/nivel1_csv/nivel1_cartel1.csv",
    "cartel2": "../niveles/nivel1_csv/nivel1_cartel2.csv",
    "choque_enemigo": "../niveles/nivel1_csv/nivel1_choque_enemigo.csv",
    "choque_personaje": "../niveles/nivel1_csv/nivel1_choque_personaje.csv",
    "enemigo": "../niveles/nivel1_csv/nivel1_enemigo.csv",
    "monedas": "../niveles/nivel1_csv/nivel1_monedas.csv",
    "mushroom_dec": "../niveles/nivel1_csv/nivel1_mushroom_dec.csv",
    "mushroom_salto": "../niveles/nivel1_csv/nivel1_mushroom_salto.csv",
    "olas": "../niveles/nivel1_csv/nivel1_olas.csv",
    "personaje": "../niveles/nivel1_csv/nivel1_personaje.csv",
    "rocas": "../niveles/nivel1_csv/nivel1_rocas.csv",
    "terreno": "../niveles/nivel1_csv/nivel1_terreno.csv",
    "troncos": "../niveles/nivel1_csv/nivel1_troncos.csv"
}